[package]
name = "pyext-myrustlib"
version = "0.1.0"
edition = "2018"
authors = ["Steve Burns <smburns47@gmail.com"]

[lib]
name = "myrustlib"
crate-type = ["dylib"]

[dependencies.cpython]
version = "0.2.1"
features = ["extension-module"]
